### PR TITLE
Random background for page

### PR DESCRIPTION
**Pull request by vikaspotluri123**
Makes it a little more livelier and doesn't take up much memory.

### CODE REVIEW

**Comment by Szczenka** [comment]
+1

**Comment by PiNotEqual3** [comment]
I like your idea. Even better would be to calculate a background color from the url. This way the same page would always have the same color.

**Comment by PiNotEqual3** [comment]
Maybe something like this?

djb2Code = function(str){
    var hash = 5381;
    for (i = 0; i < str.length; i++) {
        char = str.charCodeAt(i);
        hash = ((hash << 5) + hash) + char; /* hash * 33 + c */
    }
    return hash;
}
(djb2Code('https://github.com/') & 0xFFFFFF).toString(16).toUpperCase()


http://erlycoder.com/49/javascript-hash-functions-to-convert-string-into-integer-hash-

**Comment by PiNotEqual3** [comment]
I 

```
```

**Comment by PiNotEqual3** [comment]
This push does not work for me. background is not called and `document.getElementById("body")` is null.

Anyway I got it working by adding this into js/suspended.js below `window.onload = function()`

```
        // Hash function String to Integer
        var djb2Code = function(str){
            var hash = 5381;
            for (i = 0; i < str.length; i++) {
                char = str.charCodeAt(i);
                hash = ((hash << 5) + hash) + char; /* hash * 33 + c */
            }
            return hash;
        };
        // Background Color based on URL
        var color = '#' + (djb2Code(gsUtils.getSuspendedUrl(window.location.href)) & 0xFFFFFF).toString(16).toUpperCase();
        document.body.style.background = color;
```

Not quite sure how much I like it...

**Comment by lrq3000** [comment]
I really like the idea, but I think that the color should be computed from the domain, so that all pages of the same domain will get the same color. That's a great way to quickly skim through multiple suspended tabs to find the one you're looking for.

**Comment by meain** [comment]
How about compute the color from the prominent color on the webpage? In that way, we can relate more to the webpage that was suspended.

**Comment by vikaspotluri123** [comment]
I haven't really had much time to give this much thought!

@meain I think using the background color of the page would be best because the goal of TGS is to reduce memory usage, and computing the prominent color requires a decent amount of computation and memory consumption.

@PiNotEqual3 Sounds like something that could be implemented. We'll see how long it will take me ;)

**Comment by uhuhleuh** [comment]
Can we have several colors for the suspended page? I have 3 chrome instances always running (3 different google accounts). When they are minimized (Mac OS) I barely can distinguish them. If I could have a different suspended page's color for each, it would be a lot easier...

**Comment by deanoemcke** [comment]
@uhuhleuh hmmm.. while i agree it would be nice to be able to distinguish easily between different chrome profiles, i feel like that's a bit out of scope of this extensions purpose.

for most users that would just come across as, "you can customise the background colour of your suspended tab page" which is not something i really want people to be able to do (because I don't like custom theming in general).

**Comment by uhuhleuh** [comment]
My bad, I was not clear: do not allow custom backgrounds but offer several
*standard* colors. For example: black, dark blue, dark red dark green,
white, orange.

Thanks for responding so quickly.

dan

Em sex, 5 de out de 2018 às 22:11, Dean Oemcke <notifications@github.com>
escreveu:

**Pull request closed without merging**
