### PR TITLE
update zh_CN translation

### PR DESCRIPTION
**Pull request by shkey**
I took a moment to update all the simplified Chinese translations.

### CODE REVIEW

**Comment by deanoemcke** [comment]
@shkey wow, this is quite a major rewrite! how confident are you of the changes you are making? my expertise is limited to google translate so I have no way of telling!

also, does this mean that the traditional chinese translations are probably incorrect too?

@hermanho @goodjack @neighborhood999 do you have any comment on this PR?

**Comment by shkey** [comment]
@deanoemcke To be honest, I have made tremendous changes, most of which are basic vocabulary rather than sentence meanings. Although, I can't make the promise that my version is perfect, it's still the most suitable "Simplified Chinese Translation". As for it's correctness, I may promise you. Then, I would like to say something about the "Traditional Chinese Translation". I believe that I'm not qualified to make such comments for I'm not familiar with it. However, I may make an emphasis on the fact that both "SCT" and "TCT" have their own way of translation. "Tab", for example, we may translate it into "标签页" in "SCT" while we can call it "分页" in "TCT". To draw a conclusion, one size doesn't fit all. Habitual differences always occur in these two kinds of translations. And, if you want to make sure whether the current "TCT" is right or not, you'd better find a local person.

**Comment by hermanho** [comment]
@deanoemcke I will have a look on traditional chinese.

**Comment by hermanho** [comment]
@deanoemcke Are the these string obsoleted?
"html_suspended_modal_header", 
"html_suspended_modal_this_domain",
"html_suspended_modal_this_page",
"html_suspended_modal_temp_whitelist",
"html_suspended_modal_temp_whitelist_notice",
"html_suspended_modal_ok"

**Comment by deanoemcke** [comment]
@hermanho thanks!
and yes, those modal strings are obsolete.

**Comment by goodjack** [comment]
It looks great!

**Comment by deanoemcke** [comment]
@shkey thanks so much for this

**Comment by shkey** [comment]
@deanoemcke It's my pleasure. By the way, how long will it take for the next version to be released?

**Comment by deanoemcke** [comment]
@shkey i'd like to say the next week. but i've been saying that for months. there's just testing to do.

**Pull request merged**
