### PR TITLE
support syncing of settings

### LINKED ISSUE #262: Sync settings across computers using Chrome Sync
I really like the extension and it has saved me so much time waiting for my PC to load every tab at startup (not to mention less crashes/freezes).  I did donate too, as I think it deserves it.

My request:  I use several PCs to log into the same account.  It would be great if you could use the native Chrome sync to sync settings, so that I don't have to recreate the white list and adjust settings from scratch every time I use a different computer or even for migrating to a new computer.  That is the only inconvenience I find with the extension.

### PR DESCRIPTION
**Pull request by vapier**
Closes #262.

### CODE REVIEW

**Comment by vapier** [comment]
ping ?

**Comment by vapier** [comment]
is there something i can do to help get this merged ?

**Comment by vapier** [comment]
yes/no/maybe so ?

**Comment by Trucido** [comment]
+1
@deanoemcke is there a reason this hasn't been reviewed yet? It would be a nice feature to have.

**Comment by mediochrea** [comment]
@Trucido the extension is pretty obviously dead, someone should probably fork it at some point.

**Comment by deanoemcke** [comment]
@Trucido I have always had reservations about implementing sync of settings. Mainly because there is potentially a good use case for wanting them different of different computers. Actually mainly just the 'time to suspend' setting, which I (and I assume other users) use to 'turn off' suspension (by setting it to never). If you have a computer in which you do not want the extension to run, this is a nice way of turning it off on that machine. I could potentially just tweak your PR to sync all fields except that one?
Also, in the current implementation there is the issue of merge conflicts on the whitelist. Currently you will be potentially overriding a fully populated whitelist with a completely blank one from another computer.
It's possible that both of these issues are not major enough to prevent the PR from being accepted. Would just like to hear your opinion on it first.

**Comment by vapier** [comment]
syncing some fields but not others would be confusing.  that field in particular is something i want consistent across browsers.  so no, i don't think we should do that.

if you want the ability to deviate on a per-system instance, then could add an option (that defaults to on) called "sync settings".  that way the first time you start up a new system, it syncs, but then you can turn it off and then deviate however you want.

wrt conflicts, are you talking about going from a local->sync setup the first time ?  or in general ?  for the migration phase, we can detect that the [extension was updated](https://developer.chrome.com/extensions/runtime#event-onInstalled), and default to not syncing settings in that case.  that way no one in the field will break.  in the general case, the behavior you describe is what should happen: if i sign in to a new browser, it'll sync my settings, and if i delete all the whitelist entries, they should disappear from the others.  the only time conflicts come up is if you make changes on multiple systems but don't actually sync (e.g. you're offline).  but i'm pretty sure Chrome sync will handle conflicts intelligently there ... it'll use the latest content you modified since the conflict resolution will be in your head.

**Comment by deanoemcke** [comment]
@vapier yes. i was referring to the migration phase. and i agree that having the option to disable sync would solve both of the issues i raised. good plan!

**Comment by deanoemcke** [comment]
@mediochrea While it's true there is very little activity on this project, I do not consider it 'dead' by any means. In its current state it is still fairly bug free, and achieves its goal of freeing up memory usage fairly well.
The version of the extension available from the webstore is somewhat behind the code here on gitHub. This is due to an unfortunately side-effect of how the tabs are suspended. Any update to the extension causes all suspended tabs to disappear from chrome. While there is some tab recovery functionality within the extension, I'm hesitant to put the large userbase through this process, given that the benefits of the newer code probably don't outweigh the bad experience of the update process.
For now, I endeavour to keep the code here on gitHub relatively up-to-date and bug free.

**Comment by vapier** [comment]
i think this new version should work as requested -- there's a config option which defaults to true for new installs, and during an upgrade from <=6.30 versions, it'll be defaulted to false.

**Comment by deanoemcke** [comment]
I took a closer look at your pull request but dont think I'll be able to go ahead with it sorry. I have implemented an alternative version, but it has a few issues that I'll need to iron out first.

The main issue is that you are triggering chrome sync's based on the setOption call. This call actually happens many times and was assumed to be a fairly quick operation. Triggering chrome sync repeatedly was causing all sorts of concurrency issues when I tested your code.

The implementation I'm working on has a single listener for chrome.storage.onChanged events. However, I'm currently pondering the best way to handle edge cases where a user enables the sync flag. should their settings override all the other computers settings - or should the current computers settings be overwritten? Not a big deal, but an extra UI step which I haven't had a chance to resolve yet.

I'll keep you posted on this, but should have something committed soon.

**Comment by vapier** [comment]
are you looking at the old version ?  the new one doesn't trigger in setOption.

when a user turns on sync, then yes, their entire set of current options should get pushed out and become the latest.

**Comment by deanoemcke** [comment]
Ok. Sorry, didn't realise you'd updated it. That implementation is much nicer. 
Do you think there should be a warning when enabling sync for the first time? Just thinking about someone who has different whitelists on each computer. When you enable sync on the second one, it will override the other..

**Comment by vapier** [comment]
i've added a note to the settings page about clobbering settings and rebased onto master

building off of `chrome.storage.onChanged` instead of `gsUtils.getOption` would work too.  i didn't implement it as i'm not sure how you'd want to structure the code.

**Comment by deanoemcke** [comment]
i've merged into develop with a few small UI tweaks.
i guess it will show up as merged once i merge develop into master?

**Comment by vapier** [comment]
i think once it's been merged with master, it'll show up, or we can just close this PR.

as long as master supports syncing of settings, i'm happy ;).

**Comment by deanoemcke** [comment]
This PR didn't seem to get closed after merging with master.
Also, the final implementation of settings sync is vastly different to what was suggested here. I ended up rewriting it using a change listener on chrome.storage.
The other implementation was causing confusing bugs, and i didn't like how synced changes did not get applied immediately.
Here is the commit with the majority of the sync refactor: https://github.com/deanoemcke/thegreatsuspender/commit/a4410855eb50d52b0ff5ffb07c3af0cb93c25178

**Pull request closed without merging**
