### PR TITLE
Make the dark theme look better

### PR DESCRIPTION
**Pull request by CrazyPython**
The updated version looks like this:

### CODE REVIEW

**Comment by liamjohnston** [comment]
I like what you've done here. 
Only thing in my testing of it, I think #eee works a little better than white for `.dark #gsTopBar`, I found white a little harsh. Thoughts?

**Comment by liamjohnston** [comment]
It's also very different from the existing dark theme, I wonder if it warrants a third option, 'Really dark' :)

**Comment by CrazyPython** [comment]
> Only thing in my testing of it, I think #eee works a little better than white for .dark #gsTopBar, I found white a little harsh. Thoughts?
Maybe.

> It's also very different from the existing dark theme, I wonder if it warrants a third option, 'Really dark' :)
I don't know the codebase enough to add one... you can't make a stylish userstyle `chrome-extension://` pages, so I sent this PR.

**Comment by CrazyPython** [comment]
@liamjohnston 
I don't see much of a point in leaving everyone with a less beautiful theme... 

Comments, please?

**Comment by CrazyPython** [comment]
@deanoemcke Can I get some comments, please?

**Comment by deanoemcke** [comment]
@CrazyPython I have decided to redo the dark theme based on your input and others. Because of the relatively trivial amount of code required for the change, and because I have ended up going with different styling to your suggestions here, I will not merge this pull request.
Thanks for the input though, and a new dark theme will be out soon. Here's a preview (note, there are a few other UI changes present in this screenshot from the upcoming release):

image

**Comment by CrazyPython** [comment]
Hmm, don't you think the font weight might be a little too heavy for the lower section?

**Comment by deanoemcke** [comment]
@CrazyPython not especially. either way, it's a question for the suspended tab page in general - not just the dark theme right?
I've updated the screenshot above to make it of a similar scale to the one you initially posted.

**Comment by CrazyPython** [comment]
Perhaps we could have users submit and vote on themes they like.

**Pull request closed without merging**
