### PR TITLE
Added option to save timestamp of youtube video

### PR DESCRIPTION
**Pull request by shanedrgn**
Added the option to save the time stamp of a youtube video into the URL.

### CODE REVIEW

**Comment by shanedrgn** [comment]
This is my first time trying to contribute to a project, so if I did anything wrong or need to change code just let me know. I only made this because I got sick of having to scrub through the video finding where I was. 

I tried to make the Chinese translation in the options as accurate as possible, but I don't know enough Chinese to know if it's proper.

I also did my best to follow the same "style" of code, but if it's too different I can make changes.

**Comment by liamjohnston** [comment]
@shanedrgn It's @deanoemcke's call, but it gets a big thumbs up and a hearty 'Well done' from me :D I've been wanting this feature but hadn't done anything toward making that happen...

My only suggestion is this: I don't believe this should be a configurable setting (in the settings screen). It should just always behave this way. I want to keep the settings to a minimum, only adding settings where there isn't a clear better default. Are you happy to make this change? It looks like that would just mean removing some of the code you added.

**Comment by shanedrgn** [comment]
Uh oh. It seems to have stopped working. Please don't add this to the master branch yet! I need to fix some things in the morning!

**Comment by shanedrgn** [comment]
Nevermind. After some testing and restarting chrome, everything has worked fine. As far as  I can tell, it's safe to use

**Comment by shanedrgn** [comment]
@liamjohnston I have thought about that, but I'm sure there are many who would like an option to turn it off. What I did was extract the video ID and place it in a new URL with a timestamp. It gets rid of all the other parameters in the url.  Without the option to disable it, I could see it potentially interfering with other extensions that rely on the url. At this point, I think it's up to @deanoemcke to decide whether or not it should be in the options

**Comment by deanoemcke** [comment]
@shanedrgn thanks also for this. i'm actually on the same page as @liamjohnston about making it a permanent feature. it's very much in keeping with functionality that remembers the scroll position of the page.

is it possible to keep the original youtube url and just add the timestamp parameter?
when you say, you're worried about other extensions that rely on the url, you're talking about the original youtube url (that would show after unsuspending the tab)?

**Comment by shanedrgn** [comment]
I can make it a permanent feature instead of an option. Also, I'll work on keeping all the URL parameters.

**Comment by shanedrgn** [comment]
Okay. I made the recommended changes, and as far as I can tell, it still works

**Comment by deanoemcke** [comment]
Thanks @shanedrgn 
I'll look at merging it now. I hope you don't mind but I will probably make a few changes before merging.
I would like to add the youtube timestamp as a url param of the suspended tab url. Similar to what I do with the scroll position. That way it will survive a browser restart (the timestamp position will be stored in the url).

**Comment by shanedrgn** [comment]
It already does that. That's how I did it. It adds the param "t=[timestamp]". It still works on refresh

**Comment by deanoemcke** [comment]
ah ok. you're modifying the actual youtube url before it gets suspended. i was expecting the youtube timestamp to be a searchParam on the suspended url like how it works for scrollPos. 
but actually, doing it your way makes sense seeing as it's specific to just youtube.

i'll make some changes and then get you to review it as there's still some things I'd like to change. The codebase is not well documented so it's not always obvious the "right way" to go about something.

Also, there's a bug in that it doesn't work when tabs are suspended manually. But that will fix itself with my changes.

**Comment by shanedrgn** [comment]
Great to hear. Can't wait to read through the changes!

**Comment by deanoemcke** [comment]
I have created a new PR with my changes: https://github.com/deanoemcke/thegreatsuspender/pull/684

**Pull request closed without merging**
