### PR TITLE
Workaround for the MAJOR gsScrollPos bug

### PR DESCRIPTION
**Pull request by meteorplus**
Disabled the get cookies all for now
until a good fix is available

### CODE REVIEW

**Comment by meteorplus** [comment]
To be fixed 
https://developer.chrome.com/extensions/cookies#method-getAll

**Comment by deanoemcke** [comment]
@meteorplus As mentioned in the main issue thread, the release process is non-trivial for me, and i will not be able to do a hotfix release for this issue (that includes this PR).

As for fixing the issue more permanently, this has already been done in master branch. I am sorry this is taking so long to make it to the webstore. But it IS coming. I am now working on this project full time until this release out.

**Comment by meteorplus** [comment]
@deanoemcke so when is this going to be released ?

**Comment by DFNCTSC** [comment]
@deanoemcke Still not fixed. I'm about to just throw this extension in the trash and use Session Buddy because this is just ridiculous. This bug has existed for over a year and nothing has been done to mitigate it. It's as simple as disabling gsScrollPos from being written to certain websites -- including a whitelist for sites like youtube.

**Comment by liamjohnston** [comment]
@meteorplus It's being rolled out to the chrome web store as we speak. It's a gradual rollout, and you obviously aren't one of the lucky minority who have received the partial rollout just yet. I believe there are still a few kinks to iron out before bumping it up to 100% of users - which should be happening within the next week or so I think? 

If you really want the current latest version, you can get it from the chrome web store now - just remember to unsuspend your tabs first! You'll need to uninstall and reinstall the extension completely - hitting 'update' in your extensions page won't cut it. 

But bear in mind there is another update coming soon (with aforementioned bug fixes). My recommendation is to not take any action and wait for the (hopefully) final update to drop.

Maybe do a backup of important tabs in the meantime, as a small portion of users have reported issues with the update process.

**Pull request closed without merging**
